[project]
name = "mywallet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.7",
    "django-htmx>=1.22.0",
    "django-tailwind>=3.8.0",
    "pillow>=11.1.0",
    "whitenoise>=6.9.0",
]
